### ISSUE TITLE
[Feature] Volume control with mouse wheel

### ISSUE THREAD

**Issue by xTheEc0** [pilar6195/listen-moe-extension#13]
Would be cool if instead of setting up shortcuts (which might interfere with things, and you have to remember them) volume could be controlled by clicking the extension icon, hovering over volume slider, and scrolling up/down with a mouse.

Yes. You _could_ just click it, but my OCD wants to do it in 5% increments, not just visually : D

A workaround I have been using is to click on the volume slider ball, and then click keyboard arrow.

Priority: low

**Comment by pilar6195** [comment]
Added in f06578560e39ae273e900f7bd540faba1808bea5.

Extension update should be out now.
