### ISSUE TITLE
Could we get a license?

### ISSUE THREAD

**Issue by tekacs** [pilar6195/listen-moe-extension#2]
Just a simple request - could you add an explicit LICENSE file of some kind, at all?

MIT, GPL, Creative Commons NonCommercial with Attribution if you want especially people linking back, but an explicit license would make this saner for anyone else to work on/contribute to.

Thanks!

(Could be helpful, if you're not already familiar with this stuff: http://choosealicense.com/)

**Comment by pilar6195** [comment]
Added
