### ISSUE TITLE
Let's add play/pause hotkey 

### ISSUE THREAD

**Issue by MisaGu** [pilar6195/listen-moe-extension#3]
Is it possiable to add play/pause hotkey?!

**Comment by Pitu** [comment]
This has been a feature for quite some time already. Make sure you're running the latest version of it and go to settings 🎉

**Comment by ghost** [comment]
Hi,
I have Listen Moe 2019.8.7.1 on Firefox ESR 78.13.0. Clicking on the gear in the listen moe pop-up lead to the firefox extension's preference where there is not an option to choose a shortcut or a text that states which shortcut is available

Thanks for your app
Luca
