### ISSUE TITLE
Consider re-providing Firefox addon now that Webextensions are out

### ISSUE THREAD

**Issue by Porkepix** [pilar6195/listen-moe-extension#7]
It looks like the addon used to support Firefox previously but stopped to some times ago.
However, Firefox is now supporting Webextensions as their exclusive standard and provide a very close support, close to some small exceptions. Those should be documented on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

about:debugging in Firefox is only reporting a few bunch of errors/warnings:
```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.
Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
```
Regarding first line, background.persistent isn't currently supported by Firefox. It looks like setting this to false result in having events pages rather than background. Here this is a warning because Firefox does not support events one while it does for background.
Sources:
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/background
- https://bugzilla.mozilla.org/show_bug.cgi?id=1282971
- https://bugzilla.mozilla.org/show_bug.cgi?id=1253565#c0

Second line seems to refer to a manifest attribute not part of the spec as of now and also seems to be a warning: https://bugzilla.mozilla.org/show_bug.cgi?id=1380219

Last line is a bit more tricky.
Spec is still talking about `options_page` (https://browserext.github.io/browserext/).
However, Google deprecated this in favor of `options_ui` with Chrome 40 (https://developer.chrome.com/extensions/optionsV2) and Mozilla is also supporting this last one, but without the `chrome_style`attribute.

I also submitted the .crx extension on www.extensiontest.com
Here's the result:

<details><summary>Here's the results:</summary><p>

```
{
  "compat": [],
  "errors": [],
  "warnings": [
    {
      "message": "Unsafe assignment to innerHTML",
      "locations": [
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/sweetalert2.min.js",
          "line": 1
        },
        {
          "file": "js/jquery-3.1.0.min.js",
          "line": 2
        },
        {
          "file": "js/jquery-3.1.0.min.js",
          "line": 3
        },
        {
          "file": "js/jquery-3.1.0.min.js",
          "line": 3
        }
      ]
    }
  ]
}
```

</p></details>
About the jquery part, someone offered to get rid of it in PR #6 

The other file is minified and my knowledges in JavaScript probably are a bit low to take care about it.

Finally, it's worth noting Edge does also allow WebExtensions now, but with some spcificities either.

PS: I tested the addon through the about:debugging tool by loading it as temporary addon (I didn't packaged it). It seemed to work correctly. I didn't have the notifications, but this could be caused by the fact this mode doesn't ask for permissions. This can be the cause of this missing feature.
For what it's worth I tested on Firefox Nightly (59), but stable channel currently on 57 shouldn't have many differencies on what I listed.

**Comment by Pitu** [comment]
Hey, thanks for the feedback!
We dropped support for Firefox a few months ago after an update took 3 months in queue to be approved, and by the time it did there were already several updates done to the service. I'm not sure if their approval process for extensions has changed with these new standards you speak of, but I don't see any harm in trying again.

**Comment by Porkepix** [comment]
I guess there was maybe some lack on their side back at a time where XUL and Jetpack addons already had their death announced but Webextensions were clearly not mature enough.
Now that those are definitely dead with the release of Firefox Quantum/57, I think (and hope) they made what's needed for the amount probably way higher to addons to approve.
If this was going to take too much time, it's possible to ask news on #addon-reviewers on their IRC. Plus other channels exists around AMO (addons.mozilla.org), webextensions development and so on.
I might also try to ask news to some people if this was needed.

Especially, now differences for developping addons on the different main browsers (Firefox, Chrom[e/ium], Edge, Opera) shouldn't be that big with Webextensions adopted as a common standard, and we can hope those differences will only decrease over time.

**Comment by Pitu** [comment]
We'll see what we can do about it then. Thanks for reporting in!

**Comment by pilar6195** [comment]
Done.

https://addons.mozilla.org/en-US/firefox/addon/listen-moe-extension/
